name: Tests

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install luacheck
      run: |
        sudo apt-get update
        sudo apt-get install luarocks
        sudo luarocks install luacheck
    - uses: pre-commit/action@v3.0.0

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        nvim-version:
          - stable
          - nightly
        lean-version:
          - "leanprover-community/lean:3.49.1"
    steps:
      - uses: actions/checkout@v3

      - name: Give leanpkg (fake) greadlink on macOS
        run: cp scripts/fake_greadlink /usr/local/bin/greadlink
        if: runner.os == 'macOS'

      - name: Install elan
        run: |
            curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain "${{ matrix.lean-version }}" -y
            echo "$HOME/.elan/bin/" >> $GITHUB_PATH

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Install the Lean LSP
        run: sudo npm install -g lean-language-server
        if: contains(matrix.lean-version, 'lean:3')

      - name: Install nvim dependencies
        run: |
          mkdir packpath
          git clone --depth 1 https://github.com/AndrewRadev/switch.vim/ packpath/switch.vim
          git clone --depth 1 https://github.com/tomtom/tcomment_vim packpath/tcomment_vim
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig packpath/nvim-lspconfig
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim packpath/plenary.nvim

      - name: Run tests
        run: make TEST_SEQUENTIAL=1 test
